#!/bin/bash

# Color Palette
export BLACK=0xff181926
export WHITE=0xffcad3f5
export RED=0xffed8796
export GREEN=0xffa6da95
export BLUE=0xff8aadf4
export YELLOW=0xffeed49f
export ORANGE=0xfff5a97f
export MAGENTA=0xffc6a0f6
export GREY=0xff939ab7
export TRANSPARENT=0x00000000

# General bar colors
export BAR_COLOR=0xff1e1e2e
export BAR_BORDER_COLOR=#ffd180ff #0xa024273a
export ICON_COLOR=$WHITE # Color of all icons
export LABEL_COLOR=$WHITE # Color of all labels
# export BACKGROUND_1=0x603c3e4f
# export BACKGROUND_2=0x60494d64
export BACKGROUND_1=0xdd151515
export BACKGROUND_2=0xdd494d64
export BRACKET_DEFAULT_BACKGROUND=0x0fffffff
export BRACKET_DEFAULT_BORDER=0x22ffffff

export POPUP_BACKGROUND_COLOR=0xff1e1e2e
export POPUP_BORDER_COLOR=$WHITE

export SHADOW_COLOR=$BLACK

# Neon Tokyo theme
# export FOCUSED=#ffd180ff
export SPACE_BORDER_DEFAULT=0xffeed49f
export SPACE_BORDER_FULLSCREEN=0xbbffffff
export SPACE_BORDER_FOCUSED=0x4444ffff
export SPACE_BACKGROUD_DEFAULT=$TRANSPARENT
export SPACE_BACKGROUND_FULLSCREEN=$GREY
export SPACE_HIGHLIGHT_COLOR=0x22000000

export WINDOW_DEFAULT_COLOR=0x99ffffff
export WINDOW_HIGHLIGHT_COLOR=0xffffffff
export WINDOW_FULLSCREEN_COLOR=$BLACK
export WINDOW_FOCUSED_COLOR=0xddffffff
export WINDOW_MINIMIZED_COLOR=0x22ffffff
export WINDOW_HIDDEN_COLOR=0x66ffffff

export MIC_ON_BORDER=0xbbfc5c65
export MIC_OFF_BORDER=0x00ffffff
export MIC_DEFAULT_BACKGROUND=$BRACKET_DEFAULT_BACKGROUND

export VOLUME_BACKGROUND=$BRACKET_DEFAULT_BACKGROUND
export VOLUME_BORDER=$BRACKET_DEFAULT_BORDER

export CPU_CRITICAL=0x9ffc5c65
export CPU_HIGH=0x9ffd9644
export CPU_MEDIUM=0x9ffed330
export CPU_LOW=0x9f26de81
export CPU_IDLE=0x9f2bcbba
export CPU_DEFAULT=$BRACKET_DEFAULT_BORDER
export CPU_BACKGROUND=$BRACKET_DEFAULT_BACKGROUND

export RAM_CRITICAL=0x9ffc5c65
export RAM_HIGH=0x9ffd9644
export RAM_MEDIUM=0x9ffed330
export RAM_LOW=0x9f26de81
export RAM_IDLE=0x9f2bcbba
export RAM_DEFAULT=$BRACKET_DEFAULT_BORDER
export RAM_BACKGROUND=$BRACKET_DEFAULT_BACKGROUND

export WIFI_DEFAULT=$BRACKET_DEFAULT_BORDER
export WIFI_BACKGROUND=$BRACKET_DEFAULT_BACKGROUND
