#!/bin/bash

#
# <Base config from author's dotfiles>
#

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh" # Loads all defined icons

ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

FONT="MesloLGS NF" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=1 # All paddings use this value (icon, label, background)

ENABLE_FORK_LOADING=true

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
(cd $CONFIG_DIR/helper && make)
$CONFIG_DIR/helper/helper $HELPER > /dev/null 2>&1 &

YABAI_IGNORED_APP_REGEX="Slack .*|ESET Endpoint Antivirus"

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

# Setting up the general bar appearance of the bar
bar=(
  color=$BAR_COLOR
  border_width=0
  border_color=$BAR_BORDER_COLOR
  shadow=on
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  y_offset=1
  height=38
  margin=-2
  topmost=off
  notch_width=200
  display=main
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:13.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=30
  background.corner_radius=9
  background.border_width=2
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
)

sketchybar --default "${defaults[@]}"

# Left
source "$ITEM_DIR/apple.sh"
# source "$ITEM_DIR/spaces.sh"

# Center
source "$ITEM_DIR/spotify.sh"

# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/brew.sh"
# source "$ITEM_DIR/github.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/mic.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/stats.sh"
# source "$ITEM_DIR/cpu.sh"

#
# </Base config from author's dotfiles>
#


#
# <Dynamic Island>
#

DYNAMIC_ISLAND_DIR="$HOME/.config/sketchybar/plugins/Dynamic-Island-Sketchybar"

# Define Dynamic island custom configs here
source "$DYNAMIC_ISLAND_DIR/config.sh" # Loads Dynamic-Island config

# run helper program
ISLANDHELPER=git.crissnb.islandhelper
killall islandhelper
cd $DYNAMIC_ISLAND_DIR/helper && make
$DYNAMIC_ISLAND_DIR/helper/islandhelper $ISLANDHELPER &

# Set up your own custom sketchybar config here

###############################################

source "$DYNAMIC_ISLAND_DIR/item.sh" # Loads Dynamic-Island item

#
# </Dynamic Island>
#


#
# <Yabai>
#

YABAI_PLUGIN_DIR="$PLUGIN_DIR/yabai"

source "$ITEM_DIR/yabai.sh"
source "$ITEM_DIR/front_app.sh"

#
# </Yabai>
#


#
# <Brackets Definition>
#

status_bracket=(
  background.color=$TRANSPARENT
  background.border_color=$WHITE
)
sketchybar --add bracket status brew volume_icon memory cpu.percent \
           --set status "${status_bracket[@]}"

# sketchybar --set right border.radius=3 background.color=$BLACK

sketchybar --reorder brew battery wifi mic cpu.percent memory

sketchybar --add alias "Control Center,Bluetooth" right                            \
           --rename "Control Center,Bluetooth" bluetooth_alias                     \
           --set bluetooth_alias icon.drawing=on                                  \
                              label.drawing=on                                    \
                              alias.color="$ORANGE"                                 \
                              background.padding_right=0                           \
                              # align=right                                          \
                              # click_script="$PLUGIN_DIR/bluetooth_click.sh"

#
# </Brackets Definition>
#


# Forcing all item scripts to run (never do this outside of sketchybarrc)
# sketchybar --default background.height=30
sketchybar --update

echo "sketchybar configuation loaded.."